'''
Turtle starter code
ATLS 1300
Author: Dr. Z

Author: YOUR NAME
DATE

DESCRIPTION:
By choosing this start code, you are choosing to use a Ada Lovelace as your background 
for drawing. 

You must make sure all images you reference in the code is in the same folder as this script!
'''

import turtle #import the library of commands that you'd like to use

turtle.colormode(255)

# Create a panel to draw on. 
win = turtle.Screen()
w = 750 # width of panel
h = 750 # height of panel
win.setup(width=w, height=h) #600 x 600 is a decent size to work on. 
#You can experiment by making it the size of your screen or super tiny!

# Create a colorful background and add Ada's image to it
win.bgcolor("#703D57") #EC 2: USE AT LEAST ONE HEX VALUE
bgImg = "JustAda_Glam.gif"
stampImg = "JustAda_Glam.gif"
win.addshape(stampImg) # Now you can use Ada's image as a stamp. USE THE DOCS.

win.bgpic(bgImg) # sets the background to the selected image.
#Comment out the line above to remove the image from background

#=======Add your code here======

#framing and naming ADA
ada = turtle.Turtle()
ada.up()
ada.goto(-87,277)
ada.down()
ada.color("#f3a712")
ada.pensize(13)
ada.forward(250)
ada.right(90)
ada.forward(200)
ada.right(90)
ada.forward(250)
ada.right(90)
ada.forward(200)

#the A in ADA
ada.up()
ada.goto(-49,290)
ada.down()
ada.pensize(2)
ada.color("#669bbc")
ada.right(30)
ada.forward(50)
ada.right(120)
ada.forward(50)
ada.up()
ada.goto(-40,305)
ada.down()
ada.left(60)
ada.forward(30)

#the D in ADA
ada.up()
ada.goto(20,290)
ada.down()
ada.color("#669bbc")
ada.left(90)
ada.forward(45)
ada.right(120)
ada.forward(45)
ada.right(120)
ada.forward(45)

#the A in ADA
ada.up()
ada.goto(70,290)
ada.down()
ada.color("#669bbc")
ada.right(150)
ada.forward(50)
ada.right(120)
ada.forward(50)
ada.up()
ada.goto(79,305)
ada.down()
ada.left(60)
ada.forward(30)

#the ballons in the design

balloon = turtle.Turtle() #EC #1: 2 OR MORE TURTLE VARIABLES

#purple balloon
balloon.speed(9) #EC 3: USE THE TURTLE ANIMATION PROCESS TO ANIMATE YOUR GRAFFITI IN
balloon.up()
balloon.goto(-325,-50)
balloon.down()
balloon.color("#A682FF")
balloon.pensize(7)
balloon.begin_fill()
balloon.circle(50)
balloon.end_fill()
balloon.up()
balloon.goto(-325,-46)
balloon.down()
balloon.begin_fill()
balloon.right(60)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.end_fill()
balloon.right(150)
balloon.pensize(7)
balloon.forward(200)

#dark purple balloon
balloon.up()
balloon.goto(340,-10)
balloon.down()
balloon.left(90)
balloon.color("#52489C")
balloon.begin_fill()
balloon.circle(50)
balloon.end_fill()
balloon.up()
balloon.goto(340,-6)
balloon.down()
balloon.begin_fill()
balloon.right(60)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.end_fill()
balloon.right(150)
balloon.pensize(7)
balloon.forward(200)

#dark sea green balloon
balloon.up()
balloon.goto(500,-150)
balloon.down()
balloon.left(90)
balloon.color("#84a98c")
balloon.begin_fill()
balloon.circle(50)
balloon.end_fill()
balloon.up()
balloon.goto(500,-146)
balloon.down()
balloon.begin_fill()
balloon.right(60)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.end_fill()
balloon.right(150)
balloon.pensize(7)
balloon.forward(200)

#yellow balloon
balloon.up()
balloon.goto(-450,100)
balloon.down()
balloon.left(90)
balloon.color("#e2c044")
balloon.begin_fill()
balloon.circle(50)
balloon.end_fill()
balloon.up()
balloon.goto(-450,104)
balloon.down()
balloon.begin_fill()
balloon.right(60)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.end_fill()
balloon.right(150)
balloon.pensize(7)
balloon.forward(200)

#pink balloon
balloon.up()
balloon.goto(-575,-125)
balloon.down()
balloon.left(90)
balloon.color("#ff92c2")
balloon.begin_fill()
balloon.circle(50)
balloon.end_fill()
balloon.up()
balloon.goto(-575,-121)
balloon.down()
balloon.begin_fill()
balloon.right(60)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.end_fill()
balloon.right(150)
balloon.pensize(7)
balloon.forward(200)

#orange balloon
balloon.up()
balloon.goto(600,0)
balloon.down()
balloon.left(90)
balloon.color("#f24c00")
balloon.begin_fill()
balloon.circle(50)
balloon.end_fill()
balloon.up()
balloon.goto(600,4)
balloon.down()
balloon.begin_fill()
balloon.right(60)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.right(120)
balloon.forward(20)
balloon.end_fill()
balloon.right(150)
balloon.pensize(7)
balloon.forward(200)

#the fireworks
fireworks = turtle.Turtle()
 
fireworks.speed(0) #EC 4: USE THE TURTLE DOCS TO TURN OFF TURTLES ANIMATION. I THINK, THE DOCS SAID WHEN THE SPEED IS 0 NO AMINATION TAKES PLACE

#red firework
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.color("#a1e44d") 
fireworks.pensize(6)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)

fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.color("#ec0b43")
fireworks.pensize(4)
fireworks.right(15)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(-250,277)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)

#yellow firework
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.color("#ffc857")
fireworks.pensize(6)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)

fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.color("#ff5400")
fireworks.pensize(4)
fireworks.right(15)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)

#green firework
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.color("#ec0b43")
fireworks.pensize(6)
fireworks.right(15)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)

fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.color("#a1e44d")
fireworks.pensize(4)
fireworks.right(15)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)
fireworks.up()
fireworks.goto(250,150)
fireworks.down()
fireworks.right(30)
fireworks.forward(50)

#orange firework
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.color("#ff5400")
fireworks.pensize(6)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(80)

fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.color("#ffc857")
fireworks.pensize(4)
fireworks.right(15)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)
fireworks.up()
fireworks.goto(-500,300)
fireworks.down()
fireworks.right(30)
fireworks.forward(60)


#=======Clean up code (do not change)======
# this code ensures that your script runs correctly each time.
turtle.done()